name: 🏗️ Setup Environment
description: Install Dependencies & Deploy Workarounds

inputs:
  container:
    required: true
    description: Build container used

  install-vtk:
    required: true
    description: Wether or not to install VTK as a system dependency

runs:
  using: "composite"

  steps:
    - name: 🩹 Enable Long Paths
      shell: bash
      if: ${{ inputs.container == 'windows-latest' }}
      run: git config --system core.longpaths true

    - name: 📋 Install Dependencies
      shell: bash
      if: ${{ inputs.container == 'ubuntu-latest' }}
      run: dnf install -y make automake gcc gcc-c++ kernel-devel cmake git python3 python3-pip python3-devel

    - name: 📋 Install OpenMP
      shell: bash
      if: ${{ inputs.container == 'macos-latest' }}
      run: |
        brew reinstall --build-from-source --formula ./.github/homebrew/libomp.rb

    - name: 📋 Install VTK
      shell: bash
      if: ${{ inputs.install-vtk == 'true' }}
      run: dnf install -y vtk vtk-devel
