name: 🏗️ Setup Environment
description: Install Dependencies & Deploy Workarounds

inputs:
  os:
    required: true
    description: Operating System used

runs:
  using: "composite"

  steps:
    - name: Remove unused Homebrew taps
      shell: bash
      if: ${{ startsWith(inputs.os, 'macos-') }}
      run: |
        brew uninstall --formula azure/bicep/bicep || true
        brew untap aws/tap azure/bicep || true

    - name: 🩹 Enable Long Paths
      shell: bash
      if: ${{ inputs.os == 'windows-latest' }}
      run: git config --system core.longpaths true

    - name: 🖥️ Enable MSVC Dev Console
      if: ${{ inputs.os == 'windows-latest' }}
      uses: TheMrMilchmann/setup-msvc-dev@v4

    - name: 📋 Install OpenMP
      shell: bash
      if: ${{ startsWith(inputs.os, 'macos-') }}
      run: |
        brew install libomp
        echo "OpenMP_ROOT=$(brew --prefix)/opt/libomp" >> $GITHUB_ENV

    - name: Install Git LFS and configure (Windows)
      if: ${{ inputs.os == 'windows-latest' }}
      shell: bash
      run: |
        git lfs version || choco install git-lfs -y
        git lfs install --system
        git config --global core.autocrlf false
        echo "GIT_LFS_SKIP_SMUDGE=1" >> "$GITHUB_ENV"
        echo "CMAKE_GIT_COMMAND=$(which git)" >> "$GITHUB_ENV"

    - name: Install Git LFS and configure (macOS)
      if: ${{ startsWith(inputs.os, 'macos-') }}
      shell: bash
      run: |
        brew install git-lfs || true
        sudo git lfs install --system
        git config --global core.autocrlf false
        echo "GIT_LFS_SKIP_SMUDGE=1" >> "$GITHUB_ENV"
        echo "CMAKE_GIT_COMMAND=$(which git)" >> "$GITHUB_ENV"

    - name: 💻 Setup Deployment Target
      shell: bash
      if: ${{ startsWith(inputs.os, 'macos-') }}
      run: |
        echo "MACOSX_DEPLOYMENT_TARGET=15.0" >> $GITHUB_ENV
