name: Check If Cache Item Exists
description: Checks if the the cache item with the provided key exists
inputs:
  cache-key:
    description: Cache key
    required: true
  token:
    description: The Personal access token for the github API endpoint
    required: true
  repository:
    description: The repository "username/repo"
    required: true
outputs:
  exists:
    description: "Whether the provided key exists or not"
    value: ${{ steps.check.outputs.exists }}
runs:
  using: composite
  steps:
    - id: check
      shell: bash
      run: |
        echo exists=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ inputs.token }}" https://api.github.com/repos/${{inputs.repository}}/actions/caches | jq -r '.actions_caches|any(.key == "${{inputs.cache-key}}")') >> $GITHUB_OUTPUT

    - shell: bash
      run: echo ${{steps.check.outputs.exists}}
