function(viennaps_add_example target_name source_file)
    if(VIENNAPS_USE_GPU)
        add_gpu_executable(${target_name} _unused_target_var ${source_file})
    else()
        add_executable(${target_name} ${source_file})
        target_link_libraries(${target_name} PRIVATE ViennaPS)
    endif()

    add_dependencies(ViennaPS_Examples ${target_name})
    viennacore_setup_bat(${target_name} ${VIENNAPS_ARTIFACTS_DIRECTORY})
endfunction()
