name: Delete Cache entry
description: Deletes a cache entry that matches the provided key
inputs:
  cache-key:
    description: Cache key
    required: true
  token:
    description: The Personal access token for the github API endpoint
    required: true
  repository:
    description: The repository "username/repo"
    required: true
runs:
  using: composite
  steps:
    - id: check
      shell: bash
      run: |
        curl -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ inputs.token }}" https://api.github.com/repos/${{inputs.repository}}/actions/caches?key=${{inputs.cache-key}}
