name: 🧪 Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false

      matrix:
        config:
          - Release
          - Debug

        os:
          - macos-latest
          - windows-latest

        include:
          - os: ubuntu-latest
            config: Release
            container: ghcr.io/viennatools/vienna-builder:suite
          - os: ubuntu-latest
            config: Debug
            container: ghcr.io/viennatools/vienna-builder:suite

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    env:
      VCPKG_COMMIT: c3867e714dd3a51c272826eea77267876517ed99
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/.vcpkg-bincache

    name: "🧪 Test on ${{ matrix.os }} (⚙️: ${{ matrix.config }}, 💿: ${{ matrix.container || matrix.os }})"

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6

      - name: 🖥️ Setup Environment
        uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os }}

      - name: 📋 Install MacOS Dependencies
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install vtk embree tbb

      - name: Create vcpkg binary cache dir (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "${{ env.VCPKG_DEFAULT_BINARY_CACHE }}"

      - name: 🦥 Cache vcpkg binary (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/cache@v5
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: vcpkg-${{ matrix.os }}-${{ matrix.config }}-${{ env.VCPKG_COMMIT }}

      - name: 🛠️ Build Dependencies (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          ./vcpkg/vcpkg install --triplet x64-windows

      - name: 🏗️ Compile (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cmake -DVIENNAPS_BUILD_TESTS=ON -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -B build
          cmake --build build --config ${{ matrix.config }}

      - name: 🏗️ Compile (other)
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          cmake -DVIENNAPS_BUILD_TESTS=ON -DVIENNAPS_ENABLE_SANITIZER=ON -B build
          cmake --build build --config ${{ matrix.config }}

      - name: 🧪 Test
        run: |
          ctest --output-on-failure -E "Benchmark|Performance" -C ${{ matrix.config }} --test-dir build
