name: Check Source

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check-coding-style:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cmake-format
        run: pip3 install -U cmakelang

      - name: Apply Formatting Script
        run: ./format-project.sh

      - name: Check if code adheres to coding style
        # Checks if the source adheres to the coding style by checking whether
        # applying the formatting script changed any files
        run: |
          if [[ $(git diff-index --name-only --exit-code HEAD) ]]; then
              git diff
              exit -1
          else
              echo "Ok"
          fi
